### ISSUE TITLE
Unable to exclude files from the plugin, causing very slow builds due to our large code-generated GraphQL schemas being included

### ISSUE THREAD

**Issue by rik-iso** [yunsii/unplugin-polish-tagged-templates#5]
EDIT: see follow up comment. It's due to including files which are very expensive to parse.

---

I've root-caused a 4x in our next.js build time to the addition of this plugin (but haven't dug deeper into seeing why).

`next build` <-- the compilation step went from ~5m or less to ~20m. 

I had it added like this inside next.config.js's `webpack` block:

```
     config.plugins.push(
       polishTaggedTemplatesPlugin({
        clsTags: ['tw'],
       })
     )
```

The actual `tw` I am using is from `tagged-classnames-free` (followed its examples to get here).

Just dropping this note in case anyone else sees this issue. I'll update if I can root cause why.

**Comment by rik-iso** [comment]
Ok I actually figured it out, and it's not Next.js (and not exactly the plugin)'s fault.

Our app has a large amount of GraphQL code generated schemas, which are gigantic files as they include our entire schema definition (and are also difficult to tree shake, but that's a different problem). 

Modifying [the line in this plugin](https://github.com/yunsii/unplugin-polish-tagged-templates/blob/main/src/index.ts#L38) which excludes node_modules to also exclude our graphql codegen directory sped it up again.

Would it be possible to expose an `exclude` parameter so we can do this? I am not sure if there's a more general way to make a plugin skip a certain directory like you can do with rules. 

Happy to contribute if it sounds helpful.

**Comment by rik-iso** [comment]
(note I didn't go deeper than this, it's possible the plugin itself is inefficient and could just handle these files better, but would love maintainer's take first). ty!

**Comment by rik-iso** [comment]
From debugging I also noticed it runs on the same files over and over (based on the output). Could that possibly be an issue too? (e.g. maybe it's running on our big schema file 100s of times during the build).

**Comment by yunsii** [comment]
Thanks for your feedback, I will investigate it in this weekend, try to refactor it by https://github.com/yunsii/unplugin-polish-tagged-templates/issues/3 and optimize performance.

**Comment by yunsii** [comment]
> From debugging I also noticed it runs on the same files over and over (based on the output). Could that possibly be an issue too? (e.g. maybe it's running on our big schema file 100s of times during the build).

It's Next.js internal behavior to build client and server source code, It's best not to optimize because we don't know the principle.

**Comment by yunsii** [comment]
I haved refactored the core logic https://github.com/yunsii/unplugin-polish-tagged-templates/commit/06f35df9eeaa4e7cc12801ac3ae9acfdeaef7a74 And the performance is greatly optimized with simple benchmark https://github.com/yunsii/unplugin-polish-tagged-templates/blob/06f35df9eeaa4e7cc12801ac3ae9acfdeaef7a74/test/index.test.ts Cost on my machine:

old: 0.779ms
next: 0.234ms

Version 0.2.0-beta.1 released, please let me know if you have any questions.

**Comment by yunsii** [comment]
If extra exclude logic is still required, PR is welcome 😁

**Comment by yunsii** [comment]
Version 0.2.0-beta.2 released, support custom extra `exclude` logic.

**Comment by yunsii** [comment]
Oh no, just find that using RegExp can not cover nested taggedTemplate usage, I have to revert it with AST solution again.

**Comment by yunsii** [comment]
Version 0.2.0-beta.3 released. performance can be optimized by:

- Using RegExp to determine whether to parse AST under the hood https://github.com/yunsii/unplugin-polish-tagged-templates/blob/a5db151bf124cda070dbb4a6cf40f0aade23ca1b/src/helpers/transform.ts#L31-L37
- Custom extra `exclude` logic

Also refine test cases to cover nested taggedTemplate usage.

**Comment by yunsii** [comment]
Version 0.2.0-beta.4 released. Supported magic-string finnally. **Only nested taggedTemplate code will use AST to transform**, if a unexpected error occured by magic-string, we can use `processor` to custom processor by AST for specific file like below:

```ts
processor: (id) => {
	if (conditionOf(id)) {
		return 'ast'
	}
	return 'auto'
}
```

**Comment by rik-iso** [comment]
Thanks!! I'll have a play with this soon.

**Comment by rik-iso** [comment]
Thanks, just upgraded to 0.2.0-beta.5. Can confirm this works great.

**Comment by yunsii** [comment]
Thanks for your feedback 👌
